import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CalendarDays, ChevronRight, RefreshCw, ShieldCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { roleDataApi, type EmergencyRecord, type PatientBundle } from "../../api/roleData";
import { EmptyState, Notice, PageHeader, PatientPage, SectionCard } from "../../components/patient/PatientUI";

export function DoctorDashboard() {
  const [patients,setPatients]=useState<PatientBundle[]>([]); const [appointments,setAppointments]=useState<any[]>([]); const [emergencies,setEmergencies]=useState<EmergencyRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const[p,a,e]=await Promise.all([roleDataApi.getPatients("doctor"),roleDataApi.getAppointments(),roleDataApi.getEmergencies()]);setPatients(p.patients);setAppointments(a.appointments);setEmergencies(e.emergencies);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load clinical overview.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const activeEmergencies=emergencies.filter(item=>item.active); const pending=appointments.filter(item=>["scheduled","pending"].includes(String(item.status).toLowerCase())); const upcoming=appointments.filter(item=>!["completed","cancelled"].includes(String(item.status).toLowerCase())).slice(0,4); const attention=patients.filter(item=>item.alerts?.some((alert:any)=>!alert.read)||item.adherenceRate<80);
  const summaryCards=[{label:"Connected patients",value:patients.length,Icon:Users,style:"bg-indigo-500/10 text-indigo-300"},{label:"Active appointments",value:upcoming.length,Icon:CalendarDays,style:"bg-cyan-500/10 text-cyan-300"},{label:"Awaiting review",value:pending.length,Icon:CalendarDays,style:"bg-violet-500/10 text-violet-300"},{label:"Active emergencies",value:activeEmergencies.length,Icon:AlertTriangle,style:"bg-red-500/10 text-red-300"}];
  return <PatientPage><PageHeader eyebrow="Clinical workspace" title="Doctor overview" description="A live operational view of your authorized patient panel, appointments and emergency signals." action={<button className="patient-secondary-button" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</button>}/>{error&&<Notice tone="error"><AlertTriangle className="h-4 w-4"/>{error}</Notice>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summaryCards.map(({label,value,Icon,style})=><article key={label} className="patient-section-card flex items-center gap-3"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${style}`}><Icon className="h-5 w-5"/></span><div><p className="text-[10px] uppercase tracking-wider text-slate-400">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div></article>)}</div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><SectionCard title="Patients needing attention" description="Open alerts or adherence below 80%." action={<Link className="patient-secondary-button" to="/doctor/patients">All patients <ChevronRight className="h-3.5 w-3.5"/></Link>}>{attention.length?<div className="space-y-2">{attention.slice(0,5).map(bundle=><Link key={bundle.patient.id} to={`/doctor/patients/${bundle.patient.id}`} className="flex items-center gap-3 rounded-xl border border-[rgba(142,153,194,.14)] bg-slate-800/40 p-3 hover:border-indigo-400/30"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-500/10 font-semibold text-indigo-300">{bundle.patient.name.charAt(0)}</span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{bundle.patient.name}</h3><p className="text-xs text-slate-400">{bundle.adherenceRate}% adherence · {bundle.alerts?.filter((a:any)=>!a.read).length||0} open alerts</p></div><ChevronRight className="h-4 w-4 text-slate-500"/></Link>)}</div>:<EmptyState icon={ShieldCheck} title="No immediate signals" description="No connected patient currently has an open alert or low adherence signal."/>}</SectionCard>
      <SectionCard title="Upcoming care" description="Appointments visible to your physician account.">{upcoming.length?<div className="space-y-2">{upcoming.map(item=><article key={item.id} className="rounded-xl border border-[rgba(142,153,194,.13)] p-3"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">{item.patientName}</h3><span className="patient-status-pill is-info">{item.status}</span></div><p className="mt-1 text-xs text-slate-400">{item.title} · {item.date} at {item.time}</p></article>)}</div>:<EmptyState icon={CalendarDays} title="No upcoming appointments" description="Patient bookings and physician follow-ups will appear here."/>}</SectionCard></div>
    {activeEmergencies.length>0&&<Notice tone="error"><AlertTriangle className="h-4 w-4"/><b>{activeEmergencies.length} unresolved emergency signal{activeEmergencies.length===1?"":"s"}.</b><Link className="ml-auto font-semibold" to="/doctor/emergencies">Review now</Link></Notice>}
  </PatientPage>;
}
