import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, ChevronRight, HeartPulse, Link2, RefreshCw, Search, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { roleDataApi, type PatientBundle } from "../../api/roleData";
import { EmptyState, Field, Notice, PageHeader, PatientPage, SectionCard } from "../../components/patient/PatientUI";

export function DoctorPatientList(){
 const[patients,setPatients]=useState<PatientBundle[]>([]);const[error,setError]=useState("");const[email,setEmail]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await roleDataApi.getPatients("doctor");setPatients(data.patients);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load patients.");}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const connect=async(event:FormEvent)=>{event.preventDefault();if(!email.trim())return;setBusy(true);setMessage("");try{const result=await roleDataApi.connect(email.trim());setMessage(result.message||"Patient connected successfully.");setEmail("");await load();}catch(caught){setMessage(caught instanceof Error?caught.message:"Unable to connect patient.");}finally{setBusy(false);}};
 const visible=patients.filter(bundle=>`${bundle.patient.name} ${bundle.patient.email||""} ${bundle.patient.patientCode||""}`.toLowerCase().includes(query.toLowerCase()));
 return <PatientPage><PageHeader eyebrow="Clinical panel" title="Patients" description="Only patients connected to your physician account are shown." action={<button className="patient-secondary-button" onClick={()=>void load()} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Refresh</button>}/>{error&&<Notice tone="error"><AlertTriangle className="h-4 w-4"/>{error}</Notice>}{message&&<Notice tone={message.toLowerCase().includes("unable")||message.toLowerCase().includes("no healthsync")?"error":"success"}>{message}</Notice>}
 <div className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><SectionCard title="Connect a patient" description="Use an existing Patient account email. Authorization is created by the backend."><form className="space-y-3" onSubmit={connect}><Field label="Patient account email"><input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="patient@example.com"/></Field><button className="patient-primary-button w-full" disabled={busy}><Link2 className="h-4 w-4"/>{busy?"Connecting…":"Connect patient"}</button></form></SectionCard>
 <SectionCard title="Patient directory" description={`${patients.length} authorized patient${patients.length===1?"":"s"}`} action={<label className="relative"><Search className="absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-500"/><input className="patient-input !min-h-9 !w-44 !pl-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search patients"/></label>}>{loading?<div className="patient-ui-empty"><RefreshCw className="h-6 w-6 animate-spin"/><p>Loading patient panel…</p></div>:visible.length?<div className="space-y-2">{visible.map(bundle=>{const latest=bundle.vitals?.[0];const next=bundle.appointments?.find((item:any)=>!["cancelled","completed"].includes(String(item.status).toLowerCase()));const openAlerts=bundle.alerts?.filter((item:any)=>!item.read).length||0;return <Link key={bundle.patient.id} to={`/doctor/patients/${bundle.patient.id}`} className="grid gap-3 rounded-xl border border-[rgba(142,153,194,.14)] bg-slate-800/40 p-4 hover:border-indigo-400/30 sm:grid-cols-[1.2fr_.8fr_auto] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-500/10 font-semibold text-indigo-300">{bundle.patient.name.charAt(0)}</span><div className="min-w-0"><h3 className="truncate font-semibold">{bundle.patient.name}</h3><p className="truncate text-xs text-slate-400">{bundle.patient.email||bundle.patient.patientCode}</p></div></div><div className="grid grid-cols-2 gap-2 text-xs"><span><Activity className="mr-1 inline h-3.5 w-3.5 text-cyan-300"/>{bundle.adherenceRate}% adherence</span><span><HeartPulse className="mr-1 inline h-3.5 w-3.5 text-violet-300"/>{latest?.heartRate?`${latest.heartRate} bpm`:"No vitals"}</span><span className={openAlerts?"text-amber-300":"text-slate-400"}>{openAlerts} open alerts</span><span className="truncate text-slate-400">{next?`${next.date} ${next.time}`:"No upcoming visit"}</span></div><ChevronRight className="hidden h-4 w-4 text-slate-500 sm:block"/></Link>})}</div>:<EmptyState icon={query?Search:Users} title={query?"No matching patients":"No connected patients"} description={query?"Try a different name, email or patient code.":"Connect an existing patient account to begin authorized clinical collaboration."}/>}</SectionCard></div></PatientPage>;
}
