import { FormEvent, useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, ArrowLeft, CalendarDays, Check, Download, HeartPulse, Pill, Plus, RefreshCw, Stethoscope } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { roleDataApi, type PatientBundle } from "../../api/roleData";
import { AdherenceRing } from "../../components/ui/AdherenceRing";
import { EmptyState, Field, Notice, PatientPage, SectionCard } from "../../components/patient/PatientUI";

export function DoctorPatientDetail(){
 const{id}=useParams();const[bundle,setBundle]=useState<PatientBundle|null>(null);const[notes,setNotes]=useState<any[]>([]);const[note,setNote]=useState("");const[med,setMed]=useState({name:"",dosage:"",schedule:"",stock:"0"});const[appt,setAppt]=useState({title:"Follow-up consultation",date:"",time:""});const[feedback,setFeedback]=useState<{tone:"success"|"error";text:string}|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");
 const load=useCallback(async()=>{if(!id)return;setLoading(true);try{const[data,noteData]=await Promise.all([roleDataApi.getPatient("doctor",id),roleDataApi.getNotes(id)]);setBundle(data);setNotes(noteData.notes);setFeedback(null);}catch(caught){setFeedback({tone:"error",text:caught instanceof Error?caught.message:"Unable to load patient record."});}finally{setLoading(false);}},[id]);useEffect(()=>{void load();},[load]);
 const submitNote=async(event:FormEvent)=>{event.preventDefault();if(!note.trim()||!id)return;setBusy("note");try{await roleDataApi.addClinicalNote(id,note.trim());setNote("");await load();setFeedback({tone:"success",text:"Clinical update saved and shared with the authorized patient care record."});}catch(caught){setFeedback({tone:"error",text:caught instanceof Error?caught.message:"Unable to save clinical update."});}finally{setBusy("");}};
 const addMed=async(event:FormEvent)=>{event.preventDefault();if(!id)return;setBusy("med");try{await roleDataApi.addDoctorMedication(id,{...med,stock:Number(med.stock)});setMed({name:"",dosage:"",schedule:"",stock:"0"});await load();setFeedback({tone:"success",text:"Medication instruction added to the patient record."});}catch(caught){setFeedback({tone:"error",text:caught instanceof Error?caught.message:"Unable to add medication."});}finally{setBusy("");}};
 const schedule=async(event:FormEvent)=>{event.preventDefault();if(!id)return;setBusy("appt");try{await roleDataApi.scheduleForPatient(id,appt);setAppt({title:"Follow-up consultation",date:"",time:""});await load();setFeedback({tone:"success",text:"Follow-up scheduled and persisted for the patient."});}catch(caught){setFeedback({tone:"error",text:caught instanceof Error?caught.message:"Unable to schedule appointment."});}finally{setBusy("");}};
 function exportRecord(){if(!bundle)return;const p=bundle.patient;const content=[`HealthSync physician care summary`,`Patient: ${p.name}`,`Patient code: ${p.patientCode||`#${p.id}`}`,`Adherence: ${bundle.adherenceRate}%`,"","MEDICATIONS",...bundle.medications.map((item:any)=>`${item.name} | ${item.dosage} | ${item.schedule} | Stock ${item.stock}`),"","VITALS",...bundle.vitals.map((item:any)=>`${new Date(item.recordedAt).toLocaleString()} | HR ${item.heartRate??"—"} | BP ${item.systolic??"—"}/${item.diastolic??"—"} | Glucose ${item.glucose??"—"}`),"","APPOINTMENTS",...bundle.appointments.map((item:any)=>`${item.date} ${item.time} | ${item.title} | ${item.status}`),"","CLINICAL/CARE NOTES",...notes.map(item=>`${new Date(item.timestamp).toLocaleString()} | ${item.author}: ${item.note}`)].join("\n");const blob=new Blob([content],{type:"text/plain"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`healthsync-${p.name.replace(/\s+/g,"-").toLowerCase()}-summary.txt`;link.click();URL.revokeObjectURL(url);}
 if(loading&&!bundle)return <PatientPage><Link className="patient-secondary-button self-start" to="/doctor/patients"><ArrowLeft className="h-4 w-4"/>Patients</Link><div className="patient-ui-empty"><RefreshCw className="h-6 w-6 animate-spin"/><p>Loading authorized patient record…</p></div></PatientPage>;
 if(!bundle)return <PatientPage><Link className="patient-secondary-button self-start" to="/doctor/patients"><ArrowLeft className="h-4 w-4"/>Patients</Link>{feedback&&<Notice tone="error"><AlertTriangle className="h-4 w-4"/>{feedback.text}<button className="ml-auto font-semibold" onClick={()=>void load()}>Retry</button></Notice>}</PatientPage>;
 const p=bundle.patient;const latest=bundle.vitals?.[0];const openAlerts=bundle.alerts?.filter((item:any)=>!item.read)||[];
 return <PatientPage><div className="flex flex-wrap items-start justify-between gap-3"><div><Link className="mb-3 inline-flex items-center gap-1 text-xs text-slate-400 hover:text-white" to="/doctor/patients"><ArrowLeft className="h-3.5 w-3.5"/>Back to patients</Link><h1 className="text-2xl font-semibold tracking-tight">{p.name}</h1><p className="mt-1 text-xs text-slate-400">{p.email||p.patientCode} · Authorized physician view</p></div><button className="patient-secondary-button" onClick={exportRecord}><Download className="h-4 w-4"/>Export text summary</button></div>{feedback&&<Notice tone={feedback.tone}>{feedback.tone==="success"?<Check className="h-4 w-4"/>:<AlertTriangle className="h-4 w-4"/>}{feedback.text}</Notice>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="patient-section-card flex items-center gap-3"><AdherenceRing percent={bundle.adherenceRate} size={76}/><div><p className="text-[10px] uppercase text-slate-400">Adherence</p><strong>{bundle.adherenceRate}%</strong></div></article><article className="patient-section-card"><p className="text-[10px] uppercase text-slate-400">Latest heart rate</p><strong className="mt-2 block text-xl">{latest?.heartRate??"—"} <small className="text-xs text-slate-400">bpm</small></strong></article><article className="patient-section-card"><p className="text-[10px] uppercase text-slate-400">Medications</p><strong className="mt-2 block text-xl">{bundle.medications.length}</strong></article><article className="patient-section-card"><p className="text-[10px] uppercase text-slate-400">Open alerts</p><strong className={`mt-2 block text-xl ${openAlerts.length?"text-amber-300":""}`}>{openAlerts.length}</strong></article></div>
 <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><SectionCard title="Current medications" description="Medication instructions stored for this patient.">{bundle.medications.length?<div className="space-y-2">{bundle.medications.map((item:any)=><article key={item.id} className="flex items-center gap-3 rounded-xl bg-slate-800/45 p-3"><Pill className="h-4 w-4 text-indigo-300"/><div className="flex-1"><h3 className="text-sm font-semibold">{item.name} <span className="font-normal text-slate-400">{item.dosage}</span></h3><p className="text-xs text-slate-400">{item.schedule}</p></div><span className={`patient-status-pill ${item.stock<=6?"is-warning":"is-success"}`}>{item.stock} stock</span></article>)}</div>:<EmptyState icon={Pill} title="No medications" description="No medication instructions are stored for this patient."/>}</SectionCard><SectionCard title="Latest vitals" description="Newest recorded readings from the patient record.">{bundle.vitals.length?<div className="space-y-2">{bundle.vitals.slice(0,5).map((item:any)=><article key={item.id} className="rounded-xl bg-slate-800/45 p-3"><time className="text-[10px] text-slate-500">{new Date(item.recordedAt).toLocaleString()}</time><p className="mt-1 text-xs">HR {item.heartRate??"—"} · BP {item.systolic??"—"}/{item.diastolic??"—"} · Glucose {item.glucose??"—"}</p></article>)}</div>:<EmptyState icon={HeartPulse} title="No vital readings" description="The patient has not recorded any vitals."/>}</SectionCard></div>
 <div className="grid gap-4 xl:grid-cols-2"><SectionCard title="Clinical update" description="Stored in the shared authorized record and visible to the patient in Care Network."><form className="space-y-3" onSubmit={submitNote}><Field label="Clinical note"><textarea required rows={4} value={note} onChange={event=>setNote(event.target.value)} placeholder="Assessment, follow-up instruction or observation…"/></Field><button className="patient-primary-button" disabled={busy==="note"}><Stethoscope className="h-4 w-4"/>{busy==="note"?"Saving…":"Save clinical update"}</button></form><div className="mt-4 space-y-2 border-t border-white/10 pt-4">{notes.slice(0,5).map(item=><article key={item.id} className="rounded-xl bg-slate-800/45 p-3"><div className="flex justify-between gap-2"><b className="text-xs">{item.author}</b><time className="text-[10px] text-slate-500">{new Date(item.timestamp).toLocaleString()}</time></div><p className="mt-2 text-xs leading-5 text-slate-300">{item.note}</p></article>)}</div></SectionCard>
 <div className="space-y-4"><SectionCard title="Schedule follow-up"><form className="space-y-3" onSubmit={schedule}><Field label="Visit title"><input required value={appt.title} onChange={event=>setAppt({...appt,title:event.target.value})}/></Field><div className="patient-form-grid"><Field label="Date"><input required type="date" min={new Date().toISOString().slice(0,10)} value={appt.date} onChange={event=>setAppt({...appt,date:event.target.value})}/></Field><Field label="Time"><input required type="time" value={appt.time} onChange={event=>setAppt({...appt,time:event.target.value})}/></Field></div><button className="patient-primary-button w-full" disabled={busy==="appt"}><CalendarDays className="h-4 w-4"/>{busy==="appt"?"Scheduling…":"Schedule for patient"}</button></form></SectionCard><SectionCard title="Add medication instruction" description="This is a shared medication record entry, not a complete legal e-prescription."><form className="space-y-3" onSubmit={addMed}><div className="patient-form-grid"><Field label="Medication"><input required value={med.name} onChange={event=>setMed({...med,name:event.target.value})}/></Field><Field label="Dosage"><input required value={med.dosage} onChange={event=>setMed({...med,dosage:event.target.value})}/></Field><Field label="Schedule"><input required value={med.schedule} onChange={event=>setMed({...med,schedule:event.target.value})}/></Field><Field label="Stock"><input required type="number" min="0" value={med.stock} onChange={event=>setMed({...med,stock:event.target.value})}/></Field></div><button className="patient-primary-button w-full" disabled={busy==="med"}><Plus className="h-4 w-4"/>{busy==="med"?"Adding…":"Add medication instruction"}</button></form></SectionCard></div></div>
 <SectionCard title="Appointments and alerts"><div className="grid gap-3 lg:grid-cols-2"><div>{bundle.appointments.length?bundle.appointments.slice(0,6).map((item:any)=><article key={item.id} className="mb-2 rounded-xl bg-slate-800/45 p-3"><div className="flex justify-between gap-2"><b className="text-xs">{item.title}</b><span className="patient-status-pill">{item.status}</span></div><p className="mt-1 text-xs text-slate-400">{item.date} · {item.time}</p></article>):<EmptyState icon={CalendarDays} title="No appointments" description="No appointments are stored."/>}</div><div>{openAlerts.length?openAlerts.slice(0,6).map((item:any)=><article key={item.id} className="mb-2 rounded-xl bg-amber-500/5 p-3"><b className="text-xs text-amber-300">{item.severity}</b><p className="mt-1 text-xs text-slate-300">{item.message}</p></article>):<EmptyState icon={Activity} title="No open alerts" description="No active care alerts require review."/>}</div></div></SectionCard>
 </PatientPage>;
}
