import { useCallback, useEffect, useState } from "react";
import { Activity, AlertTriangle, Download, FileText, HeartPulse, RefreshCw, Stethoscope } from "lucide-react";
import { roleDataApi, type ReportRecord } from "../../api/roleData";
import { EmptyState, Notice, PageHeader, PatientPage, SectionCard } from "../../components/patient/PatientUI";

const icons = { adherence: Activity, vitals: HeartPulse, consultation: Stethoscope, lab: FileText } as const;
function download(report: ReportRecord) { const content = `${report.title}\nPatient: ${report.patientName}\nGenerated: ${report.generatedOn}\nAuthored by: ${report.authoredBy}\n\n${report.summary}\n`; const blob = new Blob([content], { type: "text/plain" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${report.title.replace(/\s+/g, "-").toLowerCase()}.txt`; link.click(); URL.revokeObjectURL(url); }

export function PatientReports() {
  const [reports, setReports] = useState<ReportRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await roleDataApi.getReports(); setReports(data.reports); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load reports."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  function exportAll() { const content = reports.map(report => `${report.title}\nGenerated: ${report.generatedOn}\n${report.summary}`).join("\n\n--------------------\n\n"); const blob = new Blob([content], { type: "text/plain" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "healthsync-care-summary.txt"; link.click(); URL.revokeObjectURL(url); }
  return <PatientPage><PageHeader eyebrow="Care summaries" title="Reports" description="Download text summaries generated from the health information available to your account." action={<button className="patient-secondary-button" disabled={!reports.length} onClick={exportAll}><Download className="h-4 w-4" /> Export all</button>} />{error && <Notice tone="error"><AlertTriangle className="h-4 w-4" />{error}<button className="ml-auto font-semibold" onClick={() => void load()}>Retry</button></Notice>}
    <SectionCard title="Available reports" description={`${reports.length} report${reports.length === 1 ? "" : "s"}`}>{loading ? <div className="patient-ui-empty"><RefreshCw className="h-6 w-6 animate-spin" /><p>Preparing reports from your stored data…</p></div> : reports.length ? <div className="grid gap-3 lg:grid-cols-2">{reports.map(report => { const Icon = icons[report.category]; return <article key={report.id} className="rounded-xl border border-[rgba(142,153,194,.14)] bg-[rgba(18,24,52,.55)] p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-300"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{report.title}</h3><span className="patient-status-pill is-info">{report.category}</span></div><p className="mt-1 text-[10px] text-slate-400">Generated {report.generatedOn} · {report.authoredBy}</p></div></div><p className="mt-3 text-xs leading-6 text-slate-300">{report.summary}</p><button className="patient-secondary-button mt-3" onClick={() => download(report)}><Download className="h-3.5 w-3.5" /> Download .txt</button></article>; })}</div> : <EmptyState icon={FileText} title="No reportable data yet" description="Reports will appear when sufficient medication, vital, appointment or care data is available." />}</SectionCard>
  </PatientPage>;
}
