import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Check, Send, Stethoscope, UserRound, Users } from "lucide-react";
import { roleDataApi } from "../../api/roleData";
import { EmptyState, Field, Notice, PageHeader, PatientPage, SectionCard } from "../../components/patient/PatientUI";

export function PatientCareNetwork() {
  const [connections, setConnections] = useState<any[]>([]); const [notes, setNotes] = useState<any[]>([]); const [email, setEmail] = useState(""); const [draft, setDraft] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [feedback, setFeedback] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [care, handoff] = await Promise.all([roleDataApi.getCareNetwork(), roleDataApi.getNotes()]); setConnections(care.connections); setNotes(handoff.notes); } catch (error) { setFeedback({ tone: "error", text: error instanceof Error ? error.message : "Unable to load care network." }); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function connect(event: FormEvent) { event.preventDefault(); if (!email.trim()) return; setBusy("connect"); setFeedback(null); try { const data = await roleDataApi.connect(email.trim()); setEmail(""); await load(); setFeedback({ tone: "success", text: data.message || "Care-team connection created." }); } catch (error) { setFeedback({ tone: "error", text: error instanceof Error ? error.message : "Unable to connect this account." }); } finally { setBusy(""); } }
  async function share(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; setBusy("note"); setFeedback(null); try { await roleDataApi.addNote(draft.trim()); setDraft(""); await load(); setFeedback({ tone: "success", text: "Update shared with your connected care team." }); } catch (error) { setFeedback({ tone: "error", text: error instanceof Error ? error.message : "Unable to share update." }); } finally { setBusy(""); } }
  const connection = connections[0];
  return <PatientPage><PageHeader eyebrow="Connected care" title="Care Network" description="View and connect authorized caregivers or physicians, then share persisted care updates." />{feedback && <Notice tone={feedback.tone}>{feedback.tone === "success" ? <Check className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}{feedback.text}</Notice>}
    <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><SectionCard title="Current care team" description="Connections returned by your HealthSync account.">{loading ? <p className="text-sm text-slate-400">Loading care team…</p> : connection ? <div className="space-y-2"><article className="flex items-center gap-3 rounded-xl bg-slate-800/50 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-cyan-500/10 text-cyan-300"><UserRound className="h-4 w-4" /></span><div><small className="text-[10px] uppercase text-slate-500">Caregiver</small><p className="text-sm font-semibold">{connection.caregiver?.name || "Not connected"}</p>{connection.caregiver?.email && <p className="text-[10px] text-slate-400">{connection.caregiver.email}</p>}</div></article><article className="flex items-center gap-3 rounded-xl bg-slate-800/50 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-500/10 text-violet-300"><Stethoscope className="h-4 w-4" /></span><div><small className="text-[10px] uppercase text-slate-500">Physician</small><p className="text-sm font-semibold">{connection.physician?.name || "Not connected"}</p>{connection.physician?.email && <p className="text-[10px] text-slate-400">{connection.physician.email}</p>}</div></article></div> : <EmptyState icon={Users} title="No care-team connections" description="Connect an existing caregiver or physician HealthSync account below." />}</SectionCard>
      <SectionCard title="Connect a team member" description="Patients may connect an existing caregiver or physician account by email."><form className="space-y-3" onSubmit={connect}><Field label="HealthSync account email"><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="care-team@example.com" /></Field><button className="patient-primary-button w-full" disabled={busy === "connect"}><Users className="h-4 w-4" />{busy === "connect" ? "Connecting…" : "Connect account"}</button></form></SectionCard></div>
      <SectionCard title="Shared care updates" description="Notes are stored and visible to authorized members of your care team."><form onSubmit={share}><Field label="New update"><textarea rows={3} required value={draft} onChange={e => setDraft(e.target.value)} placeholder="Share a question, observation or update…" /></Field><div className="mt-3 flex justify-end"><button className="patient-primary-button" disabled={busy === "note"}><Send className="h-4 w-4" />{busy === "note" ? "Sharing…" : "Share update"}</button></div></form><div className="mt-4 space-y-2 border-t border-[rgba(142,153,194,.14)] pt-4">{notes.length ? notes.map(note => <article key={note.id} className="rounded-xl bg-slate-800/45 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{note.author}</p><time className="text-[10px] text-slate-500">{new Date(note.timestamp).toLocaleString()}</time></div><span className="patient-status-pill mt-2">{note.authorRole}</span><p className="mt-2 text-xs leading-5 text-slate-300">{note.note}</p></article>) : <EmptyState icon={Send} title="No shared updates" description="Your first care-team note will appear here." />}</div></SectionCard></div>
  </PatientPage>;
}
