import { FormEvent, useEffect, useRef, useState } from "react";
import { AlertTriangle, Bot, CircleAlert, Send, ShieldCheck, Sparkles } from "lucide-react";
import { roleDataApi } from "../../api/roleData";
import { Notice, PageHeader, PatientPage, SectionCard } from "../../components/patient/PatientUI";

type Message = { role: "user" | "assistant"; text: string };
export function PatientAIAssistant() {
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", text: "Hello. Ask me to summarize your authorized HealthSync medications, vitals, appointments or alerts." }]);
  const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [status, setStatus] = useState<{ ollama: boolean; model: string | null; message: string } | null>(null); const endRef = useRef<HTMLDivElement>(null);
  useEffect(() => { roleDataApi.aiStatus().then(setStatus).catch(() => setStatus(null)); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, busy]);
  async function submit(event: FormEvent) { event.preventDefault(); const question = draft.trim(); if (!question || busy) return; setDraft(""); setError(""); setMessages(current => [...current, { role: "user", text: question }]); setBusy(true); try { const data = await roleDataApi.chat(question); setMessages(current => [...current, { role: "assistant", text: data.answer }]); } catch (caught) { setError(caught instanceof Error ? caught.message : "The AI service is unavailable."); } finally { setBusy(false); } }
  const prompts = ["Summarize my medications", "What are my latest recorded vitals?", "Do I have upcoming appointments?"];
  return <PatientPage><PageHeader eyebrow="Health intelligence" title="AI Assistant" description="Ask questions grounded in health information your account is authorized to access." action={<span className={`patient-status-pill ${status?.ollama ? "is-success" : "is-warning"}`}>{status?.ollama ? `Ollama · ${status.model}` : "Safe local fallback"}</span>} />
    {status && !status.ollama && <Notice tone="warning"><CircleAlert className="h-4 w-4" /><span><b>Local AI model unavailable.</b> {status.message} Responses may use the backend’s clearly identified safe fallback.</span></Notice>}{error && <Notice tone="error"><AlertTriangle className="h-4 w-4" />Your request was not completed: {error}</Notice>}
    <div className="grid min-h-0 gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><SectionCard className="flex min-h-[560px] flex-col !p-0"><div className="flex items-center gap-3 border-b border-[rgba(142,153,194,.14)] p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-500/10 text-violet-300"><Bot className="h-5 w-5" /></span><div><h2 className="font-semibold">HealthSync Assistant</h2><p className="text-[11px] text-slate-400">Authorized record context · informational support</p></div></div><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <div key={index} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[86%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-6 ${message.role === "user" ? "bg-indigo-600 text-white" : "bg-slate-800/70 text-slate-200"}`}>{message.text}</div></div>)}{busy && <div className="text-xs text-slate-400">Checking your authorized HealthSync data…</div>}<div ref={endRef} /></div><form onSubmit={submit} className="border-t border-[rgba(142,153,194,.14)] p-4"><div className="flex gap-2"><input className="patient-input min-w-0 flex-1" value={draft} onChange={e => setDraft(e.target.value)} placeholder="Ask about your HealthSync records" /><button className="patient-primary-button" disabled={busy || !draft.trim()}><Send className="h-4 w-4" /> Ask</button></div></form></SectionCard>
      <aside className="space-y-4"><SectionCard title="Suggested questions" description="These use the same grounded chat endpoint."><div className="space-y-2">{prompts.map(prompt => <button key={prompt} className="patient-secondary-button w-full !justify-start text-left" onClick={() => setDraft(prompt)}><Sparkles className="h-3.5 w-3.5" />{prompt}</button>)}</div></SectionCard><SectionCard title="Important"><div className="flex gap-2 text-xs leading-5 text-slate-400"><ShieldCheck className="h-4 w-4 shrink-0 text-indigo-300" /><p>This assistant provides informational support only. It does not diagnose conditions, prescribe treatment, or replace qualified medical advice.</p></div></SectionCard></aside></div>
  </PatientPage>;
}
